// Builds src/emoji-data.js, the names the emoji picker searches, from Unicode's
// own data. Run it again when a new emoji version is worth picking up:
//
//   node scripts/build-emoji.mjs <dir>
//
// where <dir> holds these files, fetched as they are:
//   emoji-test.txt       unicode-org/unicodetools  unicodetools/data/emoji/<version>/
//   en.xml, ko.xml       unicode-org/cldr           common/annotations/
//   en-derived.xml,      unicode-org/cldr           common/annotationsDerived/
//   ko-derived.xml       (en.xml and ko.xml there, renamed)

import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const dir = process.argv[2];
if (!dir) {
  console.error('usage: node scripts/build-emoji.mjs <dir>');
  process.exit(1);
}
const read = (name) => readFileSync(join(dir, name), 'utf8');
const SKIN_TONE = /[\u{1F3FB}-\u{1F3FF}]/u;
const bare = (emoji) => emoji.replace(/️/g, '');

function annotations(...files) {
  const names = new Map();
  const keywords = new Map();
  const unescape = (text) =>
    text.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'");
  for (const file of files) {
    for (const [, cp, tts, body] of read(file).matchAll(/<annotation cp="([^"]+)"([^>]*)>([^<]*)<\/annotation>/g)) {
      const key = bare(unescape(cp));
      if (tts.includes('type="tts"')) names.set(key, unescape(body).trim());
      else keywords.set(key, unescape(body).split('|').map((word) => word.trim()).filter(Boolean));
    }
  }
  return { names, keywords };
}

const en = annotations('en.xml', 'en-derived.xml');
const ko = annotations('ko.xml', 'ko-derived.xml');
const test = read('emoji-test.txt');
const version = /^# Version: (\S+)/m.exec(test)?.[1] ?? '?';

const rows = [];
let group = '';
for (const line of test.split('\n')) {
  const heading = /^# group: (.+)$/.exec(line);
  if (heading) group = heading[1].trim();
  const match = /^[0-9A-F ]+;\s*fully-qualified\s*#\s*(\S+)/.exec(line);
  // Skin tones and the bare components only multiply the list.
  if (!match || group === 'Component' || SKIN_TONE.test(match[1])) continue;
  const emoji = match[1];
  const key = bare(emoji);
  const enName = en.names.get(key);
  if (!enName) continue;
  const words = (list) => [...new Set(list ?? [])].join(' ').replace(/[\t\n]/g, ' ');
  // One emoji to a line: emoji, English name, English keywords, Korean name, Korean keywords.
  rows.push([emoji, enName, words(en.keywords.get(key)), ko.names.get(key) ?? '', words(ko.keywords.get(key))].join('\t'));
}

const out = `// Generated by scripts/build-emoji.mjs from Unicode emoji ${version} and the
// CLDR emoji annotations in English and Korean. Do not edit by hand.
//
// Copyright © 1991-2026 Unicode, Inc. Used under the Unicode License v3:
// https://www.unicode.org/license.txt
//
// One emoji to a line, tab-separated: the emoji, its English name and
// keywords, then its Korean name and keywords.

export const EMOJI_DATA = ${JSON.stringify(rows.join('\n'))};
`;
const target = resolve(import.meta.dirname, '../src/emoji-data.js');
writeFileSync(target, out);
console.log(`${rows.length} emoji, ${(out.length / 1024).toFixed(0)} KB -> ${target}`);
