// Starter maps. Each is just an outline -- the same format the side panel
// accepts, so they double as examples of what you can paste in.

export const SAMPLES = [
  {
    id: 'product-launch',
    name: 'Product launch',
    outline: [
      '# Product launch',
      '- Positioning',
      '  - Audience',
      '    - Ops teams',
      '    - Agencies',
      '  - Core message',
      '  - Competitive angle',
      '- Build',
      '  - Beta programme',
      '    - Recruit 20 testers',
      '    - Weekly feedback call',
      '  - Launch checklist',
      '  - Performance budget',
      '- Go to market',
      '  - Landing page',
      '  - Launch video',
      '  - Press outreach',
      '- Pricing',
      '  - Free tier',
      '  - Team plan',
      '- Support',
      '  - Help centre',
      '  - Onboarding emails',
      '- Measure',
      '  - Activation rate',
      '  - Week 4 retention',
    ].join('\n'),
  },
  {
    id: 'trip',
    name: 'Trip planner',
    outline: [
      '# Kyoto in autumn',
      '- Before leaving',
      '  - Rail pass',
      '  - Pocket wifi',
      '  - Travel insurance',
      '- Neighbourhoods',
      '  - Higashiyama',
      '    - Kiyomizu-dera at dawn',
      '    - Ninenzaka lanes',
      '  - Arashiyama',
      '    - Bamboo grove',
      '    - Riverside walk',
      '- Food',
      '  - Nishiki market',
      '  - Tofu kaiseki',
      '  - Matcha and wagashi',
      '- Day trips',
      '  - Nara deer park',
      '  - Uji tea houses',
      '- Packing',
      '  - Light rain shell',
      '  - Comfortable shoes',
    ].join('\n'),
  },
  {
    id: 'essay',
    name: 'Essay outline',
    outline: [
      '# Why cities feel alive',
      '- Thesis',
      '  - Streets are conversations',
      '- Evidence',
      '  - Sidewalk ballet',
      '    - Jane Jacobs',
      '    - Mixed use blocks',
      '  - Transit as connective tissue',
      '  - Third places',
      '- Counterpoints',
      '  - Cost of density',
      '  - Noise and privacy',
      '- Conclusion',
      '  - Design for encounters',
    ].join('\n'),
  },
];

export const DEFAULT_SAMPLE = SAMPLES[0];
